baseURL: "https://bapt0u.github.io/news.ie"
theme: PaperMod
title: The Guiness journey
# paginate: 5
# enableInlineShortcodes: true
# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
# pygmentsUseClasses: true

params:
  enableEmoji: true
  author: Bapt0u
  showReadingTime: true
  defaultTheme: auto
  showtoc: true
  homeInfoParams:
    Title: "'Morning mate :alien:"
    Content: You will find here some Irish related stuff.

  socialIcons:
    - name: Github
      url: https://github.com/Bapt0u
    - name: Youtube
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    - name: This blog (Just in case)
      url: https://Bapt0u.github.io/news.ie
